---
name: 'Build'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
  workflow_dispatch: {}
jobs:
  image:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
        with:
          submodules: true

      - uses: 'actions/cache@v3'
        with:
          path: 'cache/uxgpro-*'
          key: 'uxgpro-2'
      - uses: 'actions/cache@v3'
        with:
          path: 'firmware-mod-kit'
          key: '${{ runner.os }}-firmware-mod-kit'

      - uses: 'docker/login-action@v2'
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - if: "github.event_name != 'pull_request'"
        run: 'echo DOCKER_PUSH=true >> $GITHUB_ENV'
      - run: 'make build'
