---
name: 'Build'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
jobs:
  firmware-mod-kit:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: 'firmware-mod-kit/src'
    outputs:
      cache_key: '${{ runner.os }}/firmware-mod-kit/src'
      cache_path: 'firmware-mod-kit/src'
    steps:
      - uses: 'actions/checkout@v3'
        with:
          submodules: true
      - id: 'cache'
        uses: 'actions/cache@v3'
        with:
          path: 'firmware-mod-kit/src'
          key: '${{ runner.os }}/firmware-mod-kit/src'

      - run: 'autoreconf --force --install'
      - run: './configure --quiet'
      - run: 'make --silent'

  image:
    needs: 'firmware-mod-kit'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
        with:
          submodules: true

      - uses: 'actions/cache@v3'
        with:
          path: 'cache/uxgpro-*'
          key: "uxgpro-${{ hashFiles('Makefile') }}"
      - uses: 'actions/cache@v3'
        with:
          path: '${{ needs.firmware-mod-kit.outputs.cache_path }}'
          key: '${{ needs.firmware-mod-kit.outputs.cache_key }}'

      - uses: 'docker/login-action@v2'
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - if: "github.event_name != 'pull_request'"
        run: 'echo DOCKER_PUSH=true >> $GITHUB_ENV'
      - run: 'make build'
